version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.6.0
    restart: always
    ports:
      - '9090:9090'
    volumes:
       - prometheus_data:/prometheus
       - ./prometheus.yml:/etc/prometheus/prometheus.yml 

  snmp-exporter:
    image: prom/snmp-exporter:v0.14.0
    restart: always
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - '9116:9116'
  node-exporter:
    image: prom/node-exporter:v0.17.0
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
       - '--path.procfs=/host/proc' 
       - '--path.sysfs=/host/sys'
       - --collector.filesystem.ignored-mount-points
       - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana:5.4.2
    container_name: grafana
    volumes:
      -  grafana-storage:/var/lib/grafana
    ports:
      - 9130:3000

volumes:
  prometheus_data:
  grafana-storage:
